name: DevOps Demo

on:
  push:

jobs:
  demo:

    runs-on: ubuntu-latest

    steps:

      - name: Current Directory
        run: pwd

      - name: Current User
        run: whoami

      - name: System Info
        run: uname -a

      - name: List Files
        run: ls -la
